// Hotel
import BLOCK_HT from './BLOCK_HT.png';
import BLOCK_HT_APPR from './BLOCK_HT_APPR.png';
import BLOCK_HT_CHECK from './BLOCK_HT_CHECK.png';
import BLOCK_HT_FAN from './BLOCK_HT_FAN.png';
import BLOCK_HT_ORDER from './BLOCK_HT_ORDER.png';
import BLOCK_HT_SCH from './BLOCK_HT_SCH.png';

import BLOCK_HT_ORDER_IN from './BLOCK_HT_ORDER_IN.png';
import BLOCK_HT_ORDER_MARKET from './BLOCK_HT_ORDER_MARKET.png';
import BLOCK_HT_ORDER_SOURCE from './BLOCK_HT_ORDER_SOURCE.png';
import BLOCK_HT_ORDER_METHOD from './BLOCK_HT_ORDER_METHOD.png';
import BLOCK_HT_ORDER_MEMBER from './BLOCK_HT_ORDER_MEMBER.png';

import BLOCK_HT_SCH_SCHEDULE from './BLOCK_HT_SCH_SCHEDULE.png';
import BLOCK_HT_SCH_SHIFT from './BLOCK_HT_SCH_SHIFT.png';

import BLOCK_HT_CHECK_IN from './BLOCK_HT_CHECK_IN.png';
import BLOCK_HT_CHECK_ROOM from './BLOCK_HT_CHECK_ROOM.png';
import BLOCK_HT_CHECK_ROOM_TYPE from './BLOCK_HT_CHECK_ROOM_TYPE.png';
import BLOCK_HT_CHECK_ROOM_PRICE from './BLOCK_HT_CHECK_ROOM_PRICE.png';
import BLOCK_HT_CHECK_ROOM_STATUS from './BLOCK_HT_CHECK_ROOM_STATUS.png';
import BLOCK_HT_CHECK_USER from './BLOCK_HT_CHECK_USER.png';

import BLOCK_HT_PAY_IN from './BLOCK_HT_PAY_IN.png';
import BLOCK_HT_PAY_GOOD from './BLOCK_HT_PAY_GOOD.png';
import BLOCK_HT_PAY_REDRESS from './BLOCK_HT_PAY_REDRESS.png';

import BLOCK_HT_APPR_IN from './BLOCK_HT_APPR_IN.png';
import BLOCK_HT_APPR_RESOURCE from './BLOCK_HT_APPR_RESOURCE.png';
import BLOCK_HT_APPR_REPORT from './BLOCK_HT_APPR_REPORT.png';

export default {
    // BAG
    BLOCK_HT,
    BLOCK_HT_CHECK,
    BLOCK_HT_APPR,
    BLOCK_HT_FAN,
    BLOCK_HT_ORDER,
    BLOCK_HT_SCH,
    // BLOCK
    BLOCK_HT_ORDER_IN,
    BLOCK_HT_ORDER_MARKET,
    BLOCK_HT_ORDER_METHOD,
    BLOCK_HT_ORDER_SOURCE,
    BLOCK_HT_ORDER_MEMBER,

    BLOCK_HT_SCH_SCHEDULE,
    BLOCK_HT_SCH_SHIFT,

    BLOCK_HT_CHECK_IN,
    BLOCK_HT_CHECK_ROOM,
    BLOCK_HT_CHECK_ROOM_TYPE,
    BLOCK_HT_CHECK_ROOM_PRICE,
    BLOCK_HT_CHECK_USER,
    BLOCK_HT_CHECK_ROOM_STATUS,

    BLOCK_HT_PAY_IN,
    BLOCK_HT_PAY_GOOD,
    BLOCK_HT_PAY_REDRESS,

    BLOCK_HT_APPR_IN,
    BLOCK_HT_APPR_RESOURCE,
    BLOCK_HT_APPR_REPORT,
}