#!/usr/bin/env bash
git rm --cached --force "dist/src/hotel/index.js.map"
git rm --cached --force "dist/src/components/fore/schedule/UI.js.map"
git rm --cached --force "dist/src/components/call/order/UI.js.map"
git rm --cached --force "dist/src/kid/Kidd.Hoc.js.map"
git rm --cached --force "dist/src/kid/Kidd.js.map"
git rm --cached --force "dist/src/kid/Kidd.Debug.js.map"
git rm --cached --force "dist/src/container/login/hotel-admin/UI.js.map"
git rm --cached --force "dist/src/combination/LogStream.js.map"
git rm --cached --force "dist/src/combination/LoadingStream.js.map"
git rm --cached --force "dist/src/environment/datum.js.map"
git rm --cached --force "dist/src/environment/index.js.map"
git rm --cached --force "dist/src/control/ux-bar/TopBar.js.map"
git rm --cached --force "dist/config/modules.js.map"
git rm --cached --force "dist/.eslintrc.js.map"
